name: Deploy Azure Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd azure-functions && npm ci
    
    - name: Build frontend
      run: npm run build
    
    - name: Build Azure Functions
      run: |
        cd azure-functions
        npm run build
    
    - name: Run tests
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd azure-functions && npm ci
    
    - name: Build Azure Functions
      run: |
        cd azure-functions
        npm run build
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'my-nutrient-proxy'
        package: './azure-functions'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    
    - name: Configure app settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az functionapp config appsettings set \
            --name my-nutrient-proxy \
            --resource-group MyResourceGroup \
            --settings \
              NUTRIENT_API_KEY="${{ secrets.NUTRIENT_API_KEY }}" \
              NUTRIENT_VIEWER_API_KEY="${{ secrets.NUTRIENT_VIEWER_API_KEY }}"
    
    - name: Deploy frontend to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        app_location: "/" # Location of your source code
        api_location: "azure-functions" # Location of your Azure Functions code
        output_location: "dist" # Location of your built app 